services:
  web:
    image: nginx
    ports:
      - 8082:80
    volumes:
      - ./html

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./data
      

  users: 
    image: new_users 



